theme:
    name: material
    custom_dir: ../../overrides
    language: en
    #    features:
    #        - instant # (still experimental) feature fails to load images when folder changes
    favicon: assets/icons/favicon.ico
    logo: assets/icons/logo.svg
    logobw: assets/icons/logo-bw.svg
    palette:
        - scheme: default
          toggle:
              icon: assets/icons/dark-mode.svg
              name: Night mode
        - scheme: slate
          toggle:
              icon: assets/icons/light-mode.svg
              name: Light mode
    font:
        text: Circular Std
        code: Ubuntu Mono
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.tracking
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - toc.follow

markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:materialx.emoji.to_svg
          emoji_index: !!python/name:materialx.emoji.twemoji
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
          repo_url_shorthand: true
          user: squidfunk
          repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.snippets

plugins:
    - search # necessary for search to work
    - git-revision-date-localized
    - include-markdown
    #   - autolinks
    - awesome-pages:
    #       strict: false
    - git-revision-date-localized
    #   - minify:
    #       minify_html: true
    - redirects:
          redirect_maps:
              "redir.md": "index.md"
#    - monorepo

# Project information
site_name: Storefront User Guides
site_description: --TDB--
site_author: Virto Commerce
site_url: https://docs.virtocommerce.org/new

# Repository
repo_name: VirtoCommerce/vc-platform
repo_url: https://github.com/VirtoCommerce/vc-platform
edit_uri: edit/dev/docs/

# Copyright
copyright: Copyright &copy; 2024. All rights reserved.

# Page tree
nav:
    - Storefront and Theme:
          - Overview: overview.md
          - Navigation:
                - Homepage layout: navigation/homepage-layout.md
                - Product page layout: navigation/product-page-layout.md
          - Register and sign in:
                - Create account: registration_and_signing_in/create-account.md
                - Sign in: registration_and_signing_in/sign-in.md
                - Password management: registration_and_signing_in/password-management.md
          - Account:
                - Personal and corporate accounts: account/overview.md
                - Dashboard: account/dashboard.md
                - Profile: account/profile.md
                - Addresses: account/addresses.md
                - Orders: account/orders.md
                - Lists: account/lists.md
                - Checkout defaults: account/checkout-defaults.md
                - Quote requests: account/quote-requests.md
                - Company info: account/company-info.md
                - Company members: account/company-members.md
          - Shopping:
                - Search options: shopping/searching-for-products.md
                - Compare products: shopping/compare-products.md
                - Products lists: shopping/lists.md
                - Submit quotes: shopping/submit-quotes.md
                - Bulk orders: shopping/bulk-orders.md
                - Checkout: shopping/checkout-process.md

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/VirtoCommerce
        - icon: fontawesome/brands/facebook
          link: https://facebook.com/VirtoCommerce
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/virtocommerce?lang=en
        - icon: fontawesome/brands/instagram
          link: google.com
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/virto-commerce/
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/c/Virtocommerce/videos
    search:
        icon: assets/icons/search.svg
    rss:
        icon: assets/icons/rss.svg
    tabs_links:
        - title: Home
          url: /new
        - title: Developer Docs
          url: /new/dev_docs
        - title: User Docs
          url: /new/user_docs
    footer_links:
        - title: Support
          url: https://help.virtocommerce.com/support/home
        - title: Community
          url: https://www.virtocommerce.org/
        - title: FAQ
          url: https://www.virtocommerce.org/faq
        - title: Release Notes
          url: https://www.virtocommerce.org/c/news-digest/15

extra_javascript:
    - assets/scripts/scripts-loader.js
    - assets/scripts/scroll-menu.js

extra_css:
    - assets/stylesheets/main.css
    - assets/stylesheets/fonts.css
