title: Mutations
nav:
  - createQuoteFromCart: create-quote-from-cart.md
  - cancelQuoteRequest: cancel-quote-request.md
  - changeQuoteItemQuantity: change-quote-item-quantity.md
  - removeQuoteItem: remove-quote-item.md
  - changeQuoteComment: change-quote-comment.md
  - submitQuoteRequest: submit-quote-request.md
  - updateQuoteAddresses: update-quote-address.md
  - addQuoteAttachments: addQuoteAttachments.md
  - approveQuoteRequest: approveQuoteRequest.md
  - createQuote: createQuote.md
  - declineQuoteRequest: declineQuoteRequest.md
  - deleteQuoteAttachments: deleteQuoteAttachments.md
  - updateQuoteAttachments: updateQuoteAttachments.md
  - updateQuoteDynamicProperties: updateQuoteDynamicProperties.md
