title: Objects
nav:
  - BackInStockSubscriptionType: BackInStockSubscriptionType.md
  - BackInStockSubscriptionEdge: BackInStockSubscriptionEdge.md
  - BackInStockSubscriptionConnection: BackInStockSubscriptionConnection.md
