title: Integration
nav:
  - Elasticsearch 9:
      - Overview: elastic-search-9.md
      - Semantic Search: semantic-search-es9.md
  - Elasticsearch 8:
      - Overview: elastic-search-8.md
      - Semantic Search: semantic-search.md
  - Elastic App Search:
      - Overview: elastic-app-search-overview.md
      - Configuration: configuring-elastic-app-search.md
      - Using Analytics: using-analytics.md
      - Tuning Search Relevance: search_relevance_tuning.md
  - Elasticsearch: configuring-elasticsearch.md
  - OpenSearch: opensearch.md
  - Azure Cognitive Search: configuring-azure-cognitive-search.md
  - Algolia: algolia.md
  - Lucene: lucene.md
