title: Page Builder
nav:
  - Overview: overview.md
  - Setup: page-builder-setup.md
  - Creating New Block: create-new-block.md
  - Server Descriptors: server-descriptors.md
  - Settings: settings.md
  - Schemas: schemas.md
  - Component Context: component-context.md
  - Asset File: asset.md
  - Controls:
      - Calendar: calendar.md
      - Checkbox: checkbox.md
      - Collection: collection.md
      - Color: color.md
      - Files: files.md
      - Header: header.md
      - Images: images.md
      - Markdown: markdown.md
      - Number: number.md
      - Object: object.md
      - Paragraph: paragraph.md
      - Search: search.md
      - Select: select.md
      - String: string.md
      - Text: text.md
