title: Mutations
nav:
  - addItem: add-item.md
  - clearCart: clear-cart.md
  - selectCartItems: selectCartItems.md
  - unselectCartItems: unselectCartItems.md
  - selectAllCartItems: selectAllCartItems.md
  - unselectAllCartItems: unselectAllCartItems.md
  - changeComment: change-comment.md
  - changeCartItemPrice: change-cart-item-price.md
  - changeCartItemQuantity: change-cart-item-quantity.md
  - changeCartItemComment: change-cart-item-comment.md
  - removeCartItem: remove-cart-item.md
  - addCoupon: add-coupon.md
  - removeCoupon: remove-coupon.md
  - removeShipment: remove-shipment.md
  - addOrUpdateCartShipment: add-or-update-cart-shipment.md
  - addOrUpdateCartPayment: add-or-update-cart-payment.md
  - mergeCart: merge-cart.md
  - removeCart: remove-cart.md
  - clearShipments: clear-shipments.md
  - clearPayments: clear-payments.md
  - updateCartDynamicProperties: update-cart-dynamic-properties.md
  - updateCartItemDynamicProperties: update-cart-item-dynamic-properties.md
  - updateCartShipmentDynamicProperties: update-cart-shipment-dynamic-properties.md
  - updateCartPaymentDynamicProperties: update-cart-payment-dynamic-properties.md
  - addCartAddress: add-cart-address.md
  - createWishlist: createWishlist.md
  - changeWishlist: changeWishlist.md
  - renameWishlist: renameWishlist.md
  - removeWishlist: removeWishlist.md
  - cloneWishlist: cloneWishlist.md
  - addWishlistItem: addWishlistItem.md
  - updateWishListItems: updateWishListItems.md
  - addWishlistItems: addWishlistItems.md
  - removeWishlistItem: removeWishlistItem.md
  - moveWishlistItem: moveWishlistItem.md
  - addWishListBulkItem: add-wish-list-bulk-item.md
  - addGiftItems: addGiftItems.md
  - rejectGiftItems: rejectGiftItems.md
  - changeCartConfiguredItem: changeCartConfiguredItem.md
  - createConfiguredLineItem: createConfiguredLineItem.md
  - changeCartConfigurationItemSelected: changeCartConfigurationItemSelected.md
  - selectCartConfigurationItems: selectCartConfigurationItems.md
  - unSelectCartConfigurationItems: unSelectCartConfigurationItems.md
  - selectAllCartConfigurationItems: selectAllCartConfigurationItems.md
  - unSelectAllCartConfigurationItems: unSelectAllCartConfigurationItems.md
  - moveFromSavedForLater: moveFromSavedForLater.md
  - moveToSavedForLater: moveToSavedForLater.md
  - updateCartQuantity: updateCartQuantity.md
