INHERIT: ../mkdocs.yml
theme:
    custom_dir: ../overrides


# Project information
site_name: Documentation
site_description: Platform documentation center
site_author: Virto Commerce
site_url: https://docs.virtocommerce.org/new

# Repository
repo_name: VirtoCommerce/vc-platform
repo_url: https://github.com/VirtoCommerce/vc-platform
edit_uri: edit/dev/docs/

extra: 
    main_page:
        documentation:
            - title: User Guide
              image: assets/images/storefront-userquide.png
              description:
                - title: Getting Started
                  link: user_docs/getting-started
                - title: User Documentation
                  link: user_docs/
            - title: Developer Guide
              image: assets/images/storefront-devguide.png
              description:
                - title: Installation Guide
                  link: dev_docs/Getting-Started/Installation-Guide/windows
                - title: Architecture Overview
                  link: dev_docs/Back-End-Architecture/02-conceptual-overview
                - title: Extensibiliity
                  link: dev_docs/Extensibility/overview
                - title: Configuration reference
                  link: dev_docs/Configuration-Reference/appsettingsjson
                - title: Tutorials and How-tos
                  link: dev_docs/Tutorials-and-How-tos/Tutorials/creating-custom-module
                - title: REST API Reference
                  link: https://virtostart-demo-admin.govirto.com/docs/index.html
                - title: GraphQL API Reference
                  link: dev_docs/GraphQL-Storefront-API-Reference-xAPI/getting-started
            - title: Other Resources
              image: assets/images/storefront-other.png
              description:
                - title: Release Notes
                  link: https://github.com/VirtoCommerce/vc-platform/releases
                - title: Github
                  link: https://github.com/VirtoCommerce/vc-platform/
        release_notes:
            - title: News Digest January 2024
              link: https://www.virtocommerce.org/t/news-digest-january-2024/663
              type: Digest
              date: 8 January 2024
            - title: News Digest December 2023
              link: https://www.virtocommerce.org/t/news-digest-december-2023/651
              type: Digest
              date: 5 December 2023
            - title: News Digest November 2023
              link: https://www.virtocommerce.org/t/news-digest-november-2023/644
              type: Digest
              date: 1 November 2023
            - title: News Digest October 2023
              link: https://www.virtocommerce.org/t/news-digest-october-2023/631
              type: Digest
              date: 3 October 2023
            - title: News Digest September 2023
              link: https://www.virtocommerce.org/t/news-digest-september-2023/613
              type: Digest
              date: 5 September 2023
            - title: News Digest August 2023
              link: https://www.virtocommerce.org/t/news-digest-august-2023/602
              type: Digest
              date: 1 August 2023      
        link_cards:
                - title: Contact support
                  icon: assets/icons/contact-support.svg
                  link: https://help.virtocommerce.com/support/home
                  outlineColor: '#EA534A'
                - title: Community
                  icon: assets/icons/community.svg
                  link: https://www.virtocommerce.org/
                  outlineColor: '#EA534A'
                - title: GitHub
                  icon: assets/icons/github-outline.svg
                  link: https://github.com/VirtoCommerce
                  outlineColor: '#FF9162'
                - title: Blog
                  icon: assets/icons/blog.svg
                  link: https://virtocommerce.com/blog
                  outlineColor: '#FF9162'
