title: Objects
nav:
  - CustomerOrderType: customer-order-type.md
  - CustomerOrderConnection: customer-order-connection.md
  - OrderAddressType: order-address-type.md
  - OrderLineItemType: order-line-item-type.md
  - PaymentInType: payment-in-type.md
  - ProcessPaymentRequestResultType: process-payment-request-result-type.md
  - InputOrderBankCardInfoType: input-order-bank-card-info-type.md
  - InputOrderPaymentType: input-order-payment-type.md
  - PaymentTransactionType: payment-transaction-type.md
  - AuthorizePaymentResultType: authorize-payment-result-type.md
  - InitializePaymentResultType: initialize-payment-result-type.md
  - OrderShipmentType: order-shipment-type.md
  - OrderShippingMethodType: order-shipping-method-type.md
  - OrderShipmentItemType: order-shipment-item-type.md
  - OrderShipmentPackageType: order-shipment-package-type.md
  - InputOrderAddressType: input-order-address-type.md
  - OrderTaxDetailType: order-tax-detail-type.md
  - OrderDiscountType: order-discount-type.md
  - OrderPaymentMethodType: order-payment-method-type.md
  - LocalizedSettingResponseType: LocalizedSettingResponseType.md
  - CustomerOrderEdge: customer-order-edge.md
  - CurrencyType: currency-type.md
  - KeyValueType: key-value-type.md
  - InputKeyValueType: input-key-value-type.md
  - FilterFacet: filter-facet.md
  - RangeFacet: range-facet.md
  - TermFacet: term-facet.md
  - FacetTermType: facet-term-type.md
  - FacetRangeType: facet-range-type.md
