title: Queries
nav:
  - Organization: organization.md
  - Organizations: organizations.md
  - Contact: contact.md
  - Contacts: contacts.md
  - User: user.md
  - Role: role.md
  - Vendor: vendor.md
  - requestPasswordReset: requestPasswordReset.md
  - validatePassword: validatePassword.md
  - checkUsernameUniqueness: checkUsernameUniqueness.md
  - checkEmailUniqueness: checkEmailUniqueness.md
