title: Objects
nav:
  - Organization: OrganizationType.md
  - OrganizationConnection: OrganizationConnection.md
  - OrganizationEdge: OrganizationEdge.md
  - Contact: ContactType.md
  - ContactConnection: ContactConnection.md
  - ContactEdge: ContactEdge.md
  - User: UserType.md
  - InputCreateUserType: InputCreateUserType.md
  - InputCreateApplicationUserType: InputCreateApplicationUserType.md
  - InputUpdateApplicationUserType: InputUpdateApplicationUserType.md
  - InputApplicationUserLoginType: InputApplicationUserLoginType.md
  - CustomIdentityResultType: CustomIdentityResultType.md
  - IdentityResultType: IdentityResultType.md
  - IdentityErrorType: IdentityErrorType.md
  - IdentityErrorInfoType: IdentityErrorInfoType.md
  - Role: RoleType.md
  - InputAssignRoleType: InputAssignRoleType.md
  - InputUpdateRoleInnerType: InputUpdateRoleInnerType.md
  - InputAssignPermissionType: InputAssignPermissionType.md
  - InputAssignPermissionScopeType: InputAssignPermissionScopeType.md
  - Member: MemberType.md
  - MemberAddressType: MemberAddressType.md
  - MemberAddressConnection: MemberAddressConnection.md
  - MemberAddressEdge: MemberAddressEdge.md
  - InputMemberAddressType: InputMemberAddressType.md
  - InputDynamicPropertyValueType: InputDynamicPropertyValueType.md
  - RequestRegistrationType: RequestRegistrationType.md
  - RegisterOrganizationType: RegisterOrganizationType.md
  - RegisterContactType: RegisterContactType.md
  - RegisterAccountType: RegisterAccountType.md
  - AccountCreationResultType: AccountCreationResultType.md
  - InputRegisterOrganizationType: InputRegisterOrganizationType.md
  - InputRegisterContactType: InputRegisterContactType.md
  - InputRegisterAccountType: InputRegisterAccountType.md
  - RegistrationErrorType: RegistrationErrorType.md
  - InputRegisterByInvitationType: InputRegisterByInvitationType.md
  - InputResetPasswordByTokenType: InputResetPasswordByTokenType.md
  - InputChangePasswordType: InputChangePasswordType.md
  - Rating: rating.md
