title: Objects
nav:
  - PushMessageType: PushMessageType.md
  - PushMessageConnection: PushMessageConnection.md
  - PushMessageEdge: PushMessageEdge.md
  - InputMarkPushMessageReadType: InputMarkPushMessageReadType.md
  - InputMarkPushMessageUnreadType: InputMarkPushMessageUnreadType.md
  - FcmSettingsType: FcmSettingsType.md
  - InputAddFcmTokenType: InputAddFcmTokenType.md
  - InputDeleteFcmTokenType: InputDeleteFcmTokenType.md
