title: Objects
nav:
  - GetRecommendationsResponseType: GetRecommendationsResponseType.md
  - GetRecentlyBrowsedResponseType: GetRecentlyBrowsedResponseType.md
  - SearchHistoryResultType: SearchHistoryResultType.md
