title: CLI Tools
nav:
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Build Automation: build-automation.md
  - Package Management: package-management.md
  - Grab Migrator Utility Quickstart: grab-migrator.md
  - Cold Start Optimization and Data Migration: cold-start-and-data-migration.md
  - Installing and Updating Platform and Modules: install-and-update-platform-and-modules.md
  - Managing Platform and Modules with CLI: more-targets.md
  - Virto Cloud:
      - Overview: virto-cloud-overview.md
      - Using Virto Cloud: virto-cloud.md
