title: Getting Started
nav:
  - Quick Start: quick-start.md
  - AI Assistance: ai-quick-start.md
  - System Requirements: system-requirements.md
  - Installation-Guide
  - Skills Required for VC Developers: ../skills-required-for-VC-developers.md
