title: Objects
nav:
  - CustomerOrderStatisticsType: CustomerOrderStatisticsType.md
  - CustomerOrderStatisticsPeriodType: CustomerOrderStatisticsPeriodType.md
  - CustomerOrderStatisticsComparisonType: CustomerOrderStatisticsComparisonType.md
  - CustomerCartStatisticsType: CustomerCartStatisticsType.md
  - CustomerCartStatisticsPeriodType: CustomerCartStatisticsPeriodType.md
  - SalesRepCustomerCountsType: SalesRepCustomerCountsType.md
  - SalesRepCustomerCountsPeriodType: SalesRepCustomerCountsPeriodType.md
  - SalesRepCustomerCountsComparisonType: SalesRepCustomerCountsComparisonType.md
  - SalesRepTopSellerType: SalesRepTopSellerType.md
  - SalesRepTopSellerSortRuleType: SalesRepTopSellerSortRuleType.md
  - SalesRepTopSellerFilterRuleType: SalesRepTopSellerFilterRuleType.md
  - SalesRepOrderFilterRuleType: SalesRepOrderFilterRuleType.md
  - SalesRepCartFilterRuleType: SalesRepCartFilterRuleType.md
  - SalesRepCustomerFilterRuleType: SalesRepCustomerFilterRuleType.md
