title: Objects
nav:
  - PromotionCouponType: PromotionCouponType.md
  - PromotionCouponConnection: PromotionCouponConnection.md
  - PromotionCouponEdge: PromotionCouponEdge.md
  - DynamicContentItemType: DynamicContentItemType.md
  - EvaluateDynamicContentResultType: EvaluateDynamicContentResultType.md
