title: Storyblok
nav:
  - Overview: overview.md
  - Catalog Menu Integration: catalog-menu-integration.md
  - Category Page Integration: category-page-integration.md
  - Footer Integration: footer-integration.md
  - Index Page Integration: index-page-integration.md
  - Registering Custom Components: registering-custom-components.md
