theme:
    name: material
    custom_dir: ../overrides
    language: en
#    features:
#        - instant # (still experimental) feature fails to load images when folder changes
    favicon: assets/icons/favicon.ico
    logo: assets/icons/logo.svg
    logobw: assets/icons/logo-bw.svg
    palette:
        -   scheme: default
            toggle:
                icon: assets/icons/dark-mode.svg
                name: Night mode
        -   scheme: slate
            toggle:
                icon: assets/icons/light-mode.svg
                name: Light mode
    font:
        text: Circular Std
        code: Ubuntu Mono
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.tracking
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky

markdown_extensions:
     - abbr
     - admonition
     - attr_list
     - def_list
     - footnotes
     - md_in_html
     - toc:
         permalink: true
     - pymdownx.arithmatex:
         generic: true
     - pymdownx.betterem:
         smart_enable: all
     - pymdownx.caret
     - pymdownx.details
     - pymdownx.emoji:
         emoji_generator: !!python/name:materialx.emoji.to_svg
         emoji_index: !!python/name:materialx.emoji.twemoji
     - pymdownx.highlight:
         anchor_linenums: true
     - pymdownx.inlinehilite
     - pymdownx.keys
     - pymdownx.magiclink:
         repo_url_shorthand: true
         user: squidfunk
         repo: mkdocs-material
     - pymdownx.mark
     - pymdownx.smartsymbols
     - pymdownx.superfences:
         custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
     - pymdownx.tabbed:
         alternate_style: true
     - pymdownx.tasklist:
         custom_checkbox: true
     - pymdownx.tilde 
     - pymdownx.snippets

plugins:
    - search # necessary for search to work
    - git-revision-date-localized
    - include-markdown
 #   - autolinks
    - awesome-pages:
 #       strict: false
    - git-revision-date-localized
 #   - minify:
 #       minify_html: true
    - redirects:
        redirect_maps:
            'redir.md': 'index.md'
#    - monorepo

# Project information
site_name: User Guides
site_description: Documentation portal for Virto Commerce, an enterprise-level Microsoft .NET ecommerce platform.
site_author: Virto Commerce
site_url: https://docs.virtocommerce.org/new

# Repository
repo_name: VirtoCommerce/vc-platform
repo_url: https://github.com/VirtoCommerce/vc-platform
edit_uri: edit/dev/docs/

# Copyright
copyright: Copyright &copy; 2022. All rights reserved.

# Page tree
nav:
    - Catalog:
      - Overview: catalog/index.md
      - Terminology: catalog/glossary.md
      - Structure Chart: catalog/structure-chart.md
      - Adding New Catalog: catalog/add-new-catalog.md
      - Catalog Search: catalog/catalog-search.md
      - Managing Categories: catalog/managing-categories.md
      - Managing Products: catalog/managing-products.md
      - Managing Product Variations: catalog/managing-product-variations.md
      - Managing Properties: catalog/managing-properties.md
      - Managing Search Index: catalog/managing-search-index.md
      - Product Indexing: catalog/product-indexing.md
      - Viewing Catalog and Product Details: catalog/view-catalogs-and-physical-items.md
      - Viewing Catalog Properties: catalog/view-properties.md
    - Catalog Personalization:
      - Overview: catalog-personalization/overview.md
      - Tag Inheritance and Propagation: catalog-personalization/tag-inheritance.md
      - User Groups: catalog-personalization/user-groups.md
      - How Tos:
        - Showing or Hiding Catalog Items for Specific Users: catalog-personalization/how-tos/user-groups-for-item-view.md
        - Showing Special Prices to Specific Customers: catalog-personalization/how-tos/user-groups-for-pricing.md 
      - Settings: catalog-personalization/settings.md
    - Marketing:
      - Overview: marketing/overview.md
      - Managing Content Items: marketing/managing-content-items.md
      - Managing Content Placeholders: marketing/managing-content-placeholders.md
      - Managing Published Content: marketing/managing-published-content.md
      - Publish Conditions: marketing/publish-conditions.md
      - Adding Advertising Spot: marketing/advertising-spot.md
      - Managing Promotions: marketing/managing-promotions.md
      - Promotion Combination Policies: marketing/combining-active-promotions.md
      - Promotion Rules: marketing/promotion-rules.md
      - Settings: marketing/settings.md
    - Pricing:
      - Overview: pricing/overview.md
      - Creating New Price List: pricing/creating-new-price-list.md
      - Adding Products to Price List: pricing/adding-products-to-new-price-list.md
      - Adding New Price List Assignment: pricing/adding-new-assignment.md
      - Export Feature: pricing/export-functionality.md
      - Viewing Prices in Catalog: pricing/viewing-price-list-in-catalog.md
      - Settings: pricing/managing-pricing-module-settings.md
      - Troubleshooting Guide: pricing/troubleshooting-guide.md
    - Store:
      - Overview: store/overview.md
      - Adding New Store: store/adding-new-store.md
      - Configuring Your Store: store/configuring-store.md
      - Settings: store/settings.md
    - Contacts:
      - Overview: contacts/overview.md
      - Managing Contact Entities: contacts/managing-contacts.md
      - Search: contacts/search.md
      - Settings: contacts/settings.md
    - Contracts:
      - Overview: contracts/overview.md
      - Terminology: contracts/terminology.md
      - Creating and Terminating Contracts: contracts/creating-and-terminating-contracts.md
      - Managing Contract Prices: contracts/managing-contract-prices.md
      - Managing Contract Customers: contracts/managing-contract-customers.md
    - Notifications:
      - Overview: notifications/overview.md
      - Notification List: notifications/notification-list.md
      - Notification Templates: notifications/notification-templates.md
      - Notification Log: notifications/notification-log.md
      - Notification Layouts: notifications/notification-layouts.md
      - Settings: notifications/settings.md
    - Thumbnails:
      - Overview: thumbnails/overview.md
      - Generating Thumbnails: thumbnails/generating-thumbnails.md
      - Managing Thumbnail Options: thumbnails/thumbnail-options.md
      - Using Thumbnails: thumbnails/using-thumbnails.md
      - Settings: thumbnails/settings.md
      
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/VirtoCommerce
      - icon: fontawesome/brands/facebook
        link: https://facebook.com/VirtoCommerce
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/virtocommerce?lang=en
      - icon: fontawesome/brands/instagram
        link: google.com
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/virto-commerce/
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/c/Virtocommerce/videos
    search:
        icon: assets/icons/search.svg
    rss:
        icon: assets/icons/rss.svg
    tabs_links:
      - title: Home
        url: /new
      - title: Developer Docs
        url: /new/dev_docs
      - title: User Docs
        url: /new/user_docs    
    footer_links:
        - title: Support
          url: https://help.virtocommerce.com/support/home
        - title: Community
          url: https://www.virtocommerce.org/
        - title: FAQ
          url: https://www.virtocommerce.org/faq
        - title: Release Notes
          url: https://www.virtocommerce.org/c/news-digest/15
  
extra_javascript:
    - assets/scripts/scripts-loader.js

extra_css:
    - assets/stylesheets/main.css
    - assets/stylesheets/fonts.css
