theme:
    name: material
    custom_dir: ../overrides
    language: en
#    features:
#        - instant # (still experimental) feature fails to load images when folder changes
    favicon: assets/icons/favicon.ico
    logo: assets/icons/logo.svg
    logobw: assets/icons/logo-bw.svg
    palette:
        -   scheme: default
            toggle:
                icon: assets/icons/dark-mode.svg
                name: Night mode
        -   scheme: slate
            toggle:
                icon: assets/icons/light-mode.svg
                name: Light mode
    font:
        text: Circular Std
        code: Ubuntu Mono
    icon:
        repo: fontawesome/brands/github
markdown_extensions:
    - admonition # https://squidfunk.github.io/mkdocs-material/extensions/admonition/ (in material theme)
    - codehilite
    - meta
    # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
    - pymdownx.superfences
    - pymdownx.magiclink
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

links:
    - title: Support
      url: google.com
    - title: Community
      url: google.com
    - title: FAQ
      url: google.com
    - title: Release Notes
      url: google.com
plugins:
    - search # necessary for search to work
 #   - autolinks
    - awesome-pages:
 #       strict: false
    - git-revision-date-localized
 #   - minify:
 #       minify_html: true
    - redirects:
        redirect_maps:
            'redir.md': 'index.md'
#    - monorepo

# Project information
site_name: User Guides
site_description: Documentation portal for enterprise-level Microsoft .NET ecommerce platform Virto Commerce.
site_author: Virto Commerce
site_url: https://virtocommerce.com/docs/latest

# Repository
repo_name: VirtoCommerce/vc-platform
repo_url: https://github.com/VirtoCommerce/vc-platform
edit_uri: edit/dev/docs/

# Copyright
copyright: Copyright &copy; 2022. All rights reserved.

# Page tree
nav:
    - Catalog:
      - Overview: catalog/index.md
      - Terminology: catalog/glossary.md
      - Structure Chart: catalog/structure-chart.md
      - Adding New Catalog: catalog/add-new-catalog.md
      - Catalog Search: catalog/catalog-search.md
      - Managing Categories: catalog/managing-categories.md
      - Managing Products: catalog/managing-products.md
      - Managing Product Variations: catalog/managing-product-variations.md
      - Managing Properties: catalog/managing-properties.md
      - Managing Search Index: catalog/managing-search-index.md
      - Product Indexing: catalog/product-indexing.md
      - Search Engine Architecture: catalog/search-engine-architecture-details.md
      - Viewing Catalog and Product Details: catalog/view-catalogs-and-physical-items.md
      - Viewing Catalog Properties: catalog/view-properties.md
    - Marketing:
      - Overview: marketing/overview.md
      - Managing Content Items: marketing/managing-content-items.md
      - Managing Content Placeholders: marketing/managing-content-placeholders.md
      - Managing Published Content: marketing/managing-published-content.md
      - Publish Conditions: marketing/publish-conditions.md
      - Adding Advertising Spot: marketing/advertising-spot.md
      - Managing Promotions: marketing/managing-promotions.md
      - Promotion Combination Policies: marketing/combining-active-promotions.md
      - Promotion Rules: marketing/promotion-rules.md
    - Pricing:
      - Overview: pricing/overview.md
      - Creating New Price List: pricing/creating-new-price-list.md
      - Adding Products to Price List: pricing/adding-products-to-new-price-list.md
      - Adding New Price List Assignment: pricing/adding-new-assignment.md

  
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/VirtoCommerce
      - icon: fontawesome/brands/facebook
        link: https://facebook.com/VirtoCommerce
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/virtocommerce?lang=en
      - icon: fontawesome/brands/instagram
        link: google.com
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/virto-commerce/
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/c/Virtocommerce/videos
    search:
        icon: assets/icons/search.svg
    rss:
        icon: assets/icons/rss.svg
  
extra_javascript:
    - assets/scripts/scripts-loader.js

extra_css:
    - assets/stylesheets/main.css
    - assets/stylesheets/fonts.css
