title: GraphQL API Reference (xAPI Module)
nav:
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Authentication: authentication.md
  - Tools to Explore GraphQL:
      - Overview: tools-overview.md
      - GraphiQL: graphiql.md
      - Postman: postman.md
      - Curl: curl.md
  - Best Practices: best-practices.md
  - Extending xAPI Module: x-api-extensions.md
  - Creating Custom xAPI Module: custom-module-creation.md
  - Updating xAPI Modules: update-xapi-modules.md
  - Multiregional Development: multiregional-development.md
  - Errors and Troubleshooting: troubleshooting.md
  - AI Document Processing: PurchaseRequest
  - Back-in-Stock: Back-in-stock
  - xCart: Cart
  - xCatalog: Catalog
  - xCMS: Content
  - Customer Review: Reviews
  - xFile: File
  - xFrontend: xFrontend
  - Loyalty: Loyalty
  - xMarketing: Marketing
  - News: News
  - xOrder: Order
  - Pages: Pages
  - xPickup: xPickup
  - xProfile: Profile
  - Push Messages: Push-messages
  - Quote: Quote
  - Sales Rep: SalesRep
  - xRecommend: Recommend
  - Skyflow: Skyflow
  - Store: Store
  - Shipping: Shipping
  - White Labeling: White-labeling
