title: Operator Portal
nav:
  - Overview: overview.md
  - Master Catalog: master-catalog.md
  - Commissions: Commission-fees-setup
  - Vendors: Vendors-management
  - Registration Requests: registration-requests.md
  - Marketplace Products: marketplace-products.md
  - Offers: offers.md
  - Operator Orders: operator-orders.md
  - Quote Requests: quotes.md
  - State Machines: state-machines.md
  - Communication: communication.md
