title: Objects
nav:
  - ProductType: ProductType.md
  - ProductConnection: ProductConnection/ProductConnection.md
  - ProductEdge: ProductConnection/ProductEdge.md
  - ProductAssociationConnection: ProductAssociation/ProductAssociationConnection.md
  - ProductAssociationEdge: ProductAssociation/ProductAssociationEdge.md
  - ProductAssociation: ProductAssociation/ProductAssociation.md
  - CategoryType: category/CategoryType.md
  - CategoryConnection: category/CategoryConnection.md
  - CategoryEdge: category/CategoryEdge.md
  - CategoryDescriptionType: category/CategoryDescriptionType.md
  - DescriptionType: DescriptionType.md
  - FulfillmentCenterType: FulfillmentCenterType.md
  - FulfillmentCenterAddressType: FulfillmentCenterAddressType.md
  - FulfillmentCenterConnection: FulfillmentCenterConnection.md
  - FulfillmentCenterEdge: FulfillmentCenterEdge.md
  - VariationType: VariationType.md
  - AvailabilityData: AvailabilityData.md
  - ImageType: ImageType.md
  - PriceType: Price/PriceType.md
  - TierPriceType: Price/TierPriceType.md
  - CatalogDiscountType: Price/CatalogDiscountType.md
  - PropertyType: Property/Property.md
  - PropertyConnection: Property/PropertyConnection.md
  - PropertyEdge: Property/PropertyEdge.md
  - PropertyDictItemConnection: Property/PropertyDictItemConnection.md
  - PropertyDictItemEdge: Property/PropertyDictItemEdge.md
  - PropertyDictItem: Property/PropertyDictItem.md
  - Asset: Asset.md
  - PageInfo: PageInfo.md
  - InventoryInfo: InventoryInfo.md
  - SeoInfo: SeoInfo.md
  - OutlineType: OutlineType.md
  - OutlineItemType: OutlineItemType.md
  - Breadcrumb: Breadcrumb.md
  - CommonVendor: CommonVendor/Commonvendor.md
  - Rating: CommonVendor/Rating.md
  - VideoConnection: VideoConnection/VideoConnection.md
  - VideoEdge: VideoConnection/VideoEdge.md
  - VideoType: VideoConnection/VideoType.md
  - FilterFacet: Facets/FilterFacet.md
  - RangeFacet: Facets/RangeFacet.md
  - FacetRangeType: Facets/FacetRangeType.md
  - TermFacet: Facets/TermFacet.md
  - FacetTermType: Facets/facetTermType.md
  - BrandType: BrandType.md
  - BrandConnection: BrandConnection.md
  - BrandEdge: BrandEdge.md
  - SlugInfoResponseType: SlugInfoResponseType.md
  - ProductSuggestionsQueryResponseType: ProductSuggestionsQueryResponseType.md
