theme:
    name: material
    custom_dir: ../overrides
    language: en
    #    features:
    #        - instant # (still experimental) feature fails to load images when folder changes
    favicon: legacy/media/favicon.ico
    logo: assets/icons/logo.svg
    logobw: assets/icons/logo-bw.svg
    palette:
        - scheme: default
          toggle:
              icon: assets/icons/dark-mode.svg
              name: Night mode
        - scheme: slate
          toggle:
              icon: assets/icons/light-mode.svg
              name: Light mode
    font:
        text: Circular Std
        code: Ubuntu Mono
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.tabs
        - --md-code-bg-color
        - search.highlight
        - search.share
        - search.suggest
markdown_extensions:
    - admonition # https://squidfunk.github.io/mkdocs-material/extensions/admonition/ (in material theme)
    - codehilite
    - meta
    # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
    - pymdownx.superfences
    - pymdownx.magiclink
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search # necessary for search to work
    #   - autolinks
    - awesome-pages:
    #       strict: false
    - git-revision-date-localized
    #   - minify:
    #       minify_html: true
    - redirects:
          redirect_maps:
              "redir.md": "index.md"

# Project information
site_name: Documentation
site_description: Storefront documentation center
site_author: Virto Commerce
site_url: https://docs.virtocommerce.org/new

# Repository
repo_name: VirtoCommerce/vc-theme-b2b-vue
repo_url: https://github.com/VirtoCommerce/vc-theme-b2b-vue
edit_uri: edit/dev/docs/

# Copyright
copyright: Copyright &copy; 2024. All rights reserved.

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/VirtoCommerce
        - icon: fontawesome/brands/facebook
          link: https://facebook.com/VirtoCommerce
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/virtocommerce?lang=en
        - icon: fontawesome/brands/instagram
          link: google.com
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/virto-commerce/
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/c/Virtocommerce/videos
    search:
        icon: assets/icons/search.svg
    rss:
        icon: assets/icons/rss.svg
    footer_links:
        - title: Support
          url: https://help.virtocommerce.com/support/home
        - title: Community
          url: https://www.virtocommerce.org/
        - title: FAQ
          url: https://www.virtocommerce.org/faq
        - title: Release Notes
          url: https://www.virtocommerce.org/c/news-digest/15
    main_page:
        documentation:
            - title: User Guide
              image: assets/images/storefront-userquide.png
              description:
                - title: Registration
                  link: user_docs/registration_and_signing_in/create-account
                - title: Navigation
                  link: user_docs/navigation/homepage-layout
                - title: Shopping
                  link: user_docs/shopping/searching-for-products
            - title: Developer Guide
              image: assets/images/storefront-devguide.png
              description:
                - title: Getting Started
                  link: dev_docs/getting-started/quickstart-on-windows
                - title: ASP.NET Core Storefront Runtime
                  link: dev_docs/asp-net-core-storefront-runtime/overview
                - title: Vue.js Starter Theme
                  link: dev_docs/vue-js-starter-theme/overview
                - title: Integrations
                  link: dev_docs/integrations/prerender_io
            - title: Other Resources
              image: assets/images/storefront-other.png
              description:
                - title: Release Notes
                  link: https://github.com/VirtoCommerce/vc-storefront/releases
                - title: Github
                  link: https://github.com/VirtoCommerce/vc-storefront/
        release_notes:
            - title: News Digest January 2024
              link: https://www.virtocommerce.org/t/news-digest-january-2024/663
              type: Digest
              date: 8 January 2024
            - title: News Digest December 2023
              link: https://www.virtocommerce.org/t/news-digest-december-2023/651
              type: Digest
              date: 5 December 2023
            - title: News Digest November 2023
              link: https://www.virtocommerce.org/t/news-digest-november-2023/644
              type: Digest
              date: 1 November 2023
            - title: News Digest October 2023
              link: https://www.virtocommerce.org/t/news-digest-october-2023/631
              type: Digest
              date: 3 October 2023
            - title: News Digest September 2023
              link: https://www.virtocommerce.org/t/news-digest-september-2023/613
              type: Digest
              date: 5 September 2023
            - title: News Digest August 2023
              link: https://www.virtocommerce.org/t/news-digest-august-2023/602
              type: Digest
              date: 1 August 2023
        # top_cards:
            # -   title: Architect
            #     icon: assets/icons/package.svg
            #     description: I need to build the platform's architecture or learn how I can do that.
            #     link: https://docs.virtocommerce.org/architecture-center/B2B-multiregional/
            # - title: User Guide
            #   icon: assets/icons/person.svg
            #   description: --TBD--
            #   link: user_docs
            # - title: Developer Guide
            #   icon: assets/icons/code-square.svg
            #   description: --TBD--
            #   link: dev_docs
            # -   title: Business Analyst
            #     icon: assets/icons/briefcase.svg
            #     description: I need to know how to implement Virto solutions across my team or externally.
            #     link: https://docs.virtocommerce.org/BA%20docs/
        # wide_cards:
        #     -   title: B2C solution
        #         icon: b2b-second.svg
        #         description: Learn how to build an online store your customers will buy goods and services from.
        #         link: under-construction
        #     -   title: E-commerce platform
        #         icon: platform.svg
        #         description: Explore Virto's e-commerce opportunities and learn how to leverage them.
        #         link: under-construction
        #     -   title: VirtoCloud
        #         icon: cloud.svg
        #         description: Cloud techs are currently in the forefront of the IT industry. Learn how to them with Virto.
        #         link: under-construction
        #     -   title: Marketplace
        #         icon: marketplace.svg
        #         description: Virto Commerce allows you to build your very own unique online marketplace. See how!
        #         link: under-construction
        # education:
        #     - title: Videos
        #       description: Explore our video tutorials
        #       image: assets/icons/videos.png
        #       link: https://www.youtube.com/c/Virtocommerce
        #     - title: Tech Blog
        #       description: Hints, tips, and so much more!
        #       image: assets/icons/articles.png
        #       link: https://www.virtocommerce.org/
        #     - title: Case Studies
        #       description: Best case studies provided by our dev team
        #       image: assets/icons/videos-second.png
        #       link: https://virtocommerce.com/case-studies
        #     - title: Code samples
        #       description: Most used code samples
        #       image: assets/icons/stories.png
        #       link: https://github.com/VirtoCommerce/vc-sample
        link_cards:
                - title: Contact support
                  icon: assets/icons/contact-support.svg
                  link: https://help.virtocommerce.com/support/home
                  outlineColor: '#EA534A'
                - title: Community
                  icon: assets/icons/community.svg
                  link: https://www.virtocommerce.org/
                  outlineColor: '#EA534A'
                - title: GitHub
                  icon: assets/icons/github-outline.svg
                  link: https://github.com/VirtoCommerce
                  outlineColor: '#FF9162'
                - title: Blog
                  icon: assets/icons/blog.svg
                  link: https://virtocommerce.com/blog
                  outlineColor: '#FF9162'
    all_topics:
        footer:
            - iconSrc: "./assets/icons/release-notes.svg"
              title: "Release Notes"
              url: "#"
            - iconSrc: "./assets/icons/support.svg"
              title: "Support"
              url: "#"
            - iconSrc: "./assets/icons/github.svg"
              title: "GitHub"
              url: "#"
extra_javascript:
    - assets/scripts/scripts-loader.js
    - assets/scripts/scroll-menu.js

extra_css:
    - assets/stylesheets/main.css
    - assets/stylesheets/fonts.css
