title: Objects
nav:
  - CartType: cart-type.md
  - CartConnection: cart-connection.md
  - CartEdge: cart-edge.md
  - CartShipmentItemType: cart-shipment-item-type.md
  - CartAddressType: cart-address-type.md
  - MoneyType: money-type.md
  - CurrencyType: currency-type.md
  - TaxDetailType: tax-detail-type.md
  - ShipmentType: shipment-type.md
  - ShipmentMethodType: shipping-method-type.md
  - PaymentType: payment-type.md
  - PaymentMethodType: payment-method-type.md
  - DiscountType: discount-type.md
  - GiftItemType: gift-item-type.md
  - CouponType: coupon-type.md
  - DynamicPropertyType: dynamic-property-type.md
  - DynamicPropertyValueType: dynamic-property-value-type.md
  - LineItemType: line-item-type.md
  - DictionaryItemType: dictionary-item-type.md
  - DictionaryItemConnection: dictionary-item-connection.md
  - ValidationErrorType: validation-error-type.md
  - ErrorParameterType: error-parameter-type.md
  - WishlistType: wishlist-type.md
  - WishListEdge: wishlist-edge.md
  - WishlistConnection: wishlist-connection.md
  - WishlistScopeType: wishlist-scope-type.md
  - InputNewWishlistItemType: InputNewWishlistItemType.md
  - InputUpdateWishlistLineItemType: InputUpdateWishlistLineItemType.md
  - InputUpdateWishlistItemsType: InputUpdateWishlistItemsType.md
  - BulkWishlistType: bulk-wishlist-type.md
  - ConfigurationSectionType: ConfigurationSectionType.md
  - CartConfigurationItemType: CartConfigurationItemType.md
  - ConfigurationLineItemType: ConfigurationLineItemType.md
  - ConfigurationQueryResponseType: ConfigurationQueryResponseType.md
  - ConfigurationItemsResponseType: ConfigurationItemsResponseType.md
  - ConfigurationSectionInput: ConfigurationSectionInput.md
  - ConfigurationSectionKeyInput: ConfigurationSectionKeyInput.md
  - ConfigurableProductOptionInput: ConfigurableProductOptionInput.md
  - ConfigurableProductOptionKeyInput: ConfigurableProductOptionKeyInput.md
  - InputUpdateCartQuantityItem: InputUpdateCartQuantityItem.md
