title: Objects
nav:
  - pickupLocationType: pickupLocationType.md
  - pickupLocationConnection: pickupLocationConnection.md
  - PickupLocationAddressType: PickupLocationAddressType.md
  - pickupAddressType: pickupAddressType.md
  - cartPickupLocationConnection: CartPickupLocationConnection.md
  - pickupLocationEdge: pickupLocationEdge.md
  - productPickupAvailabilityType: ProductPickupAvailabilityType.md
  - productPickupLocation: ProductPickupLocation.md
  - productPickupLocationConnection: ProductPickupLocationConnection.md
  - productPickupLocationEdge: ProductPickupLocationEdge.md
