title: Account
nav:
  - Personal and Corporate Accounts: overview.md
  - Purchasing:
      - Dashboard: dashboard.md
      - Orders: orders.md
      - Lists: lists.md
      - Quote Requests: quote-requests.md
      - Purchase Requests: purchase-requests.md
      - Saved for Later: saved-for-later.md
      - Back-in-Stock List: back-in-stock-list.md
  - Marketing:
      - Coupons and Promotions: coupons.md
      - Notifications: notifications.md
      - Points History: points-history.md
  - Corporate:
      - Company Info: company-info.md
      - Company Members: company-members.md
  - User:
      - Profile: profile.md
      - Change Password: change-password.md
      - Addresses: addresses.md
      - Saved Credit Cards: saved-credit-cards.md
