title: Objects
nav:
  - ChangeOrganizationLogoResultType: ChangeOrganizationLogoResultType.md
  - WhiteLabelingSettingsType: WhiteLabelingSettingsType.md
  - FaviconType: FaviconType.md
  - MenuLinkType: MenuLinkType.md
