theme:
    name: material
    custom_dir: ../overrides
    language: en
#    features:
#        - instant # (still experimental) feature fails to load images when folder changes
    favicon: assets/icons/favicon.ico
    logo: assets/icons/logo.svg
    logobw: assets/icons/logo-bw.svg
    palette:
        -   scheme: default
            toggle:
                icon: assets/icons/dark-mode.svg
                name: Night mode
        -   scheme: slate
            toggle:
                icon: assets/icons/light-mode.svg
                name: Light mode
    font:
        text: Circular Std
        code: Ubuntu Mono
    icon:
        repo: fontawesome/brands/github
markdown_extensions:
    - admonition # https://squidfunk.github.io/mkdocs-material/extensions/admonition/ (in material theme)
    - codehilite
    - meta
    # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
    - pymdownx.superfences
    - pymdownx.magiclink
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

links:
    - title: Support
      url: google.com
    - title: Community
      url: google.com
    - title: FAQ
      url: google.com
    - title: Release Notes
      url: google.com
plugins:
    - search # necessary for search to work
 #   - autolinks
    - awesome-pages:
 #       strict: false
    - git-revision-date-localized
 #   - minify:
 #       minify_html: true
    - redirects:
        redirect_maps:
            'redir.md': 'index.md'
#    - monorepo

# Project information
site_name: Developer Center
site_description: Documentation portal for enterprise-level Microsoft .NET ecommerce platform Virto Commerce.
site_author: Virto Commerce
site_url: https://docs.virtocommerce.org/new

# Repository
repo_name: VirtoCommerce/vc-docs
repo_url: https://github.com/vc-docs
edit_uri: edit/dev/docs/

# Copyright
copyright: Copyright &copy; 2022. All rights reserved.

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - System Requirements: Getting-Started/system-requirements-in-progress.md
    - Installation Guide:
      - Windows:
        - Prerequisites: Getting-Started/Installation-Guide/Installing-on-Windows/01-installation-windows-on-premises-prerequisites.md
        - Installing with Precompiled Binaries: Getting-Started/Installation-Guide/Installing-on-Windows/02-installation-windows-on-premises-precompiled-binaries.md
        - Installing with CLI: Getting-Started/Installation-Guide/Installing-on-Windows/03-installation-windows-on-premises-CLI.md
      - Post Installation Steps:
        - Setting Up Self Signed SSL Certificate: Getting-Started/Post-Installation-Steps/01-setting-up-self-signed-ssl-cert.md
        - Configuring Email Notifications: Getting-Started/Post-Installation-Steps/02-configuring-email-notifications.md
        - Configuring Asset Blob Storage: Getting-Started/Post-Installation-Steps/03-configuring-asset-blob-storage.md
        - Importing Sample Data: Getting-Started/Post-Installation-Steps/04-importing-sample-data.md
  - Fundamentals:
    - Caching:
      - Overview: Fundamentals/Caching/01-overview-in-progress.md
      - Cache Configuration: Fundamentals/Caching/02-cache-configuration.md
      - Setting Up Redis Backplane for Scaling Out: Fundamentals/Caching/03-setting-up-Redis.md
    - Configuration Reference:
      - Appsettings.json: Fundamentals/Configuration-Reference/appsettingsjson.md
    - Data Import:
      - Main Concept: Fundamentals/Data-Import/01-main-concept.md
      - Building Custom Importer: Fundamentals/Data-Import/02-building-custom-importer.md
    - Indexed Search:
      - Overview: Fundamentals/Indexed-Search/overview.md 
      - Search Query Syntax Reference: Fundamentals/Indexed-Search/search-query-syntax-reference.md
      - Indexing:
        - Overview: Fundamentals/Indexed-Search/indexing/overview.md
        - Indexing in Platform Manager: Fundamentals/Indexed-Search/indexing/indexing-in-platform-manager.md
        - Blue-Green Indexing: Fundamentals/Indexed-Search/indexing/blue-green-indexing.md
      - Search:
          - Overview: Fundamentals/Indexed-Search/search/overview.md
          - Faceted Search Overview and Configuration: Fundamentals/Indexed-Search/search/faceted-search.md
      - Integration:
        - Configuring Elasticsearch: Fundamentals/Indexed-Search/integration/configuring-elasticsearch.md
        - Configuring Azure Cognitive Search: Fundamentals/Indexed-Search/integration/configuring-azure-cognitive-search.md
        - Elastic App Search Overview: Fundamentals/Indexed-Search/integration/elastic-app-search-overview.md
        - Configuring Elastic App Search: Fundamentals/Indexed-Search/integration/configuring-elastic-app-search.md
    - Modularity:
      - Overview: Fundamentals/Modularity/01-overview-IN-PROGRESS.md
      - Folder Structure: Fundamentals/Modularity/02-folder-structure-IN-PROGRESS.md
      - Versioning and Dependencies: Fundamentals/Modularity/03-versioning-and-dependencies.md
      - Loading Modules into App Process: Fundamentals/Modularity/04-loading-modules-into-app-process.md
      - Best Practices: Fundamentals/Modularity/05-best-practices.md
      - Module.manifest File: Fundamentals/Modularity/06-module-manifest-file.md
    - Extensibility:
      - Overview: Fundamentals/Extensibility/overview.md
    - Event Driven Development:
      - Using Domain Events: Fundamentals/Event-Driven-Development/using-domain-events.md
    - Integration:
      - Payment Gateways:
        - Registering New Payment Method: Fundamentals/Integration/Payment-Gateways/new-payment-method-registration.md
      - Shipping Providers:
        - Registering New Shipping Method: Fundamentals/Integration/Shipping-Providers/new-shipping-method-registration.md
      - Tax Providers:
        - Registering New Tax Provider: Fundamentals/Integration/Tax-Providers/new-tax-provider-registration.md
    - Dynamic Properties:
      - Overview: Fundamentals/Dynamic-Properties/overview.md
    - Security:
      - Extending Authorizarion Policies: Fundamentals/Security/extending-authorization-policies.md
  - Back End Architecture:
    - Tech Stack: Back-End-Architecture/01-tech-stack.md
    - Conceptual Overview: Back-End-Architecture/02-conceptual-overview-in-progress.md
  - Platform Manager:
    - Style Guide: Platform-Manager/style-guide.md
    - UI Scroll Directive: Platform-Manager/ui-scroll-directive.md
    - Extensibility Points:
      - Extending Main Menu: Platform-Manager/Extensibility-Points/extending-main-menu.md
      - Blades and Navigation: Platform-Manager/Extensibility-Points/blades-and-navigation.md
      - Metaform: Platform-Manager/Extensibility-Points/metaform.md
      - Widgets: Platform-Manager/Extensibility-Points/widgets.md
      - Extending Grid Columns: Platform-Manager/Extensibility-Points/extending-grid-columns.md
      - Blade Toolbar: Platform-Manager/Extensibility-Points/blade-toolbar.md
  - GraphQL Storefront API Reference (xAPI):
    - Overview: GraphQL-Storefront-API-Reference-xAPI/index.md
    - Getting Started: GraphQL-Storefront-API-Reference-xAPI/getting-started.md
    - Catalog:
      - Overview: GraphQL-Storefront-API-Reference-xAPI/Catalog/overview.md
      - Queries:
        - Product: GraphQL-Storefront-API-Reference-xAPI/Catalog/queries/01-product.md
        - Products: GraphQL-Storefront-API-Reference-xAPI/Catalog/queries/02-products.md
        - Categories: GraphQL-Storefront-API-Reference-xAPI/Catalog/queries/03-categories.md
        - Properties: GraphQL-Storefront-API-Reference-xAPI/Catalog/queries/04-properties.md
        - Property: GraphQL-Storefront-API-Reference-xAPI/Catalog/queries/05-property.md
        - Fulfullment Center: GraphQL-Storefront-API-Reference-xAPI/Catalog/queries/06-fulfillment-center.md
        - Fulfullment Centers: GraphQL-Storefront-API-Reference-xAPI/Catalog/queries/07-fulfillment-centers.md
      - Objects:
        - ProductType: GraphQL-Storefront-API-Reference-xAPI/Catalog/objects/01-ProductType.md
        - CategoryType: GraphQL-Storefront-API-Reference-xAPI/Catalog/objects/02-CategoryType.md
        - FulfullmentCenterType: GraphQL-Storefront-API-Reference-xAPI/Catalog/objects/03-FulfillmentCenterType.md
      - Examples:
        - Full Text Search: GraphQL-Storefront-API-Reference-xAPI/Catalog/examples/01-full-text-search.md
        - Fuzzy Search: GraphQL-Storefront-API-Reference-xAPI/Catalog/examples/02-fuzzy-search.md
        - Filter Syntax: GraphQL-Storefront-API-Reference-xAPI/Catalog/examples/03-filter-syntax.md
        - Filtering: GraphQL-Storefront-API-Reference-xAPI/Catalog/examples/04-filtering.md
        - Facets: GraphQL-Storefront-API-Reference-xAPI/Catalog/examples/05-facets.md
        - Multi Select Faceting Search: GraphQL-Storefront-API-Reference-xAPI/Catalog/examples/06-multi-select-faceting-search.md
    - Cart:
      - Overview: GraphQL-Storefront-API-Reference-xAPI/Cart/overview.md
      - Queries:
        - Query List: GraphQL-Storefront-API-Reference-xAPI/Cart/queries/query-list.md
        - Cart: GraphQL-Storefront-API-Reference-xAPI/Cart/queries/cart.md
        - Cart Connection: GraphQL-Storefront-API-Reference-xAPI/Cart/queries/cart-connection.md
      - Mutations:
        - Overview: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/01-overview.md
        - Mutation List: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/02-mutation-list.md
        - AddItem: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/03-add-item.md
        - ClearCart: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/04-clear-cart.md
        - ChangeComment: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/05-change-comment.md
        - ChangeCartItemPrice: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/06-change-cart-item-price.md
        - ChangeCartItemQuantity: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/07-change-cart-item-quantity.md
        - ChangeCartItemComment: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/08-change-cart-item-comment.md
        - RemoveCartItem: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/09-remove-cart-item.md
        - AddCoupon: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/10-add-coupon.md
        - RemoveCoupon: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/11-remove-coupon.md
        - RemoveShipment: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/12-remove-shipment.md
        - AddOrUpdateCartShipment: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/13-add-or-update-cart-shipment.md
        - AddOrUpdateCartPayment: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/14-add-or-update-cart-payment.md
        - ValidateCoupon: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/15-validate-coupon.md
        - MergeCart: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/16-merge-cart.md
        - RemoveCart: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/17-remove-cart.md
        - ClearShipments: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/18-clear-shipments.md
        - ClearPayments: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/19-clear-payments.md
        - UpdateCartDynamicProperties: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/20-update-cart-dynamic-properties.md
        - UpdateCartItemDynamicProperties: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/21-update-cart-item-dynamic-properties.md
        - UpdateCartShipmentDynamicProperties: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/22-update-cart-shipment-dynamic-properties.md
        - UpdateCartPaymentDynamicProperties: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/23-update-cart-payment-dynamic-properties.md
        - AddCartAddress: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/24-add-cart-address.md
        - AddWishListBulkItem: GraphQL-Storefront-API-Reference-xAPI/Cart/mutations/25-add-wish-list-bulk-item.md
      - Objects:
        - CartType: GraphQL-Storefront-API-Reference-xAPI/Cart/objects/cart-type.md
    - Order:
        - Overview: GraphQL-Storefront-API-Reference-xAPI/Order/overview.md
        - Queries:
          - Overview: GraphQL-Storefront-API-Reference-xAPI/Order/queries/overview.md
          - Order: GraphQL-Storefront-API-Reference-xAPI/Order/queries/order.md
          - Order Connection: GraphQL-Storefront-API-Reference-xAPI/Order/queries/order-connection.md
        - Mutations:
          - Mutation List: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/01-mutation-list.md
          - CreateOrderFromCart: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/02-create-order-from-cart.md
          - ChangeOrderStatus: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/03-change-order-status.md
          - ConfirmOrderPayment: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/04-confirm-order-payment.md
          - CancelOrderPayment: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/05-cancel-order-payment.md
          - UpdateOrderDynamicProperties: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/06-update-order-dynamic-properties.md
          - UpdateOrderItemDynamicProperties: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/07-update-order-item-dynamic-properties.md
          - UpdateOrderShipmentDynamicProperties: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/08-update-order-shipment-dynamic-properties.md
          - UpdateOrderPaymentDynamicProperties: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/09-update-order-payment-dynamic-properties.md
          - InitializePayment: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/10-initialize-payment.md
          - AuthorizePayment: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/11-authorize-payment.md
          - AddOrUpdateOrderPayment: GraphQL-Storefront-API-Reference-xAPI/Order/mutations/12-add-or-update-order-payment.md
        - Objects:
          - OrderType: GraphQL-Storefront-API-Reference-xAPI/Order/objects/order-type.md
    - xAPI Extensions: GraphQL-Storefront-API-Reference-xAPI/x-api-extensions.md
    - Troubleshooting: GraphQL-Storefront-API-Reference-xAPI/troubleshooting.md
    - Samples and Recommendations: GraphQL-Storefront-API-Reference-xAPI/recommendations.md
  - Tutorials and How-tos:
    - Tutorials:
      - Creating Custom Module: Tutorials-and-How-tos/Tutorials/creating-custom-module.md
      - Extending Domain Models: Tutorials-and-How-tos/Tutorials/extending-domain-models.md
  
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/VirtoCommerce
      - icon: fontawesome/brands/facebook
        link: https://facebook.com/VirtoCommerce
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/virtocommerce?lang=en
      - icon: fontawesome/brands/instagram
        link: google.com
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/virto-commerce/
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/c/Virtocommerce/videos
    search:
        icon: assets/icons/search.svg
    rss:
        icon: assets/icons/rss.svg
  
extra_javascript:
    - assets/scripts/scripts-loader.js

extra_css:
    - assets/stylesheets/main.css
    - assets/stylesheets/fonts.css
