title: Objects
nav:
  - PageDocumentConnection: PageDocumentConnection.md
  - PageDocumentEdge: PageDocumentEdge.md
  - PageDocumentType: PageDocumentType.md
  - SlugInfoResponseType: SlugInfoResponseType.md
