title: Extensibility Points
nav:
  - Extending Main Menu: extending-main-menu.md
  - Blades and Navigation: blades-and-navigation.md
  - Metaform: metaform.md
  - Widgets: widgets.md
  - Extending Grid Columns: extending-grid-columns.md
  - Blade Toolbar: blade-toolbar.md
