nav:
  - About Virto Commerce Platform: getting-to-know-platform.md
  - Overview: index.md
  - Getting-Started
  - Back-End-Architecture
  - Security-and-Compliance
  - CLI-tools
  - Fundamentals
  - Configuration-Reference
  - Platform-Manager
  - GraphQL-Storefront-API-Reference-xAPI
  - Extensibility
  - Operations
  - Tutorials-and-How-tos
  - Updating-Virto-Commerce-Based-Project
  - custom-apps-development
