title: Objects
nav:
  - PickupAddressType: PickupAddressType.md
  - PickupLocationType: PickupLocationType.md
  - PickupLocationEdge: PickupLocationEdge.md
  - PickupLocationConnection: PickupLocationConnection.md
